package com.korniykom.echojournal.echos.presentation.components

import androidx.compose.foundation.layout.IntrinsicSize
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material3.IconButtonDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.korniykom.echojournal.core.presentation.designsystem.theme.EchoJournalTheme
import com.korniykom.echojournal.core.presentation.designsystem.theme.MoodPrimary25
import com.korniykom.echojournal.core.presentation.designsystem.theme.MoodPrimary35
import com.korniykom.echojournal.core.presentation.designsystem.theme.MoodPrimary80
import com.korniykom.echojournal.core.presentation.utils.formatMMSS
import com.korniykom.echojournal.echos.presentation.models.MoodUi
import com.korniykom.echojournal.echos.presentation.models.PlaybackState
import kotlin.random.Random
import kotlin.time.Duration
import kotlin.time.Duration.Companion.seconds
